import Head from "next/head";
import Image from "next/image";
import Header from "../components/Header";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Hulu 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <h1 className="text-3xl font-bold underline">Hello world!</h1> */}

      {/* Header  */}
      <Header />
      {/* Nav  */}

      {/* Results  */}
    </div>
  );
}
